version: "3"

vars:
  NPX: '{{.NPX | default "npx"}}'
  NPM: '{{.NPM | default "pnpm"}}'
  WEB_HOST: localhost
  WEB_PORT: 4173

includes:
  proto:
    taskfile: ../proto
    dir: ../proto

tasks:
  prepare: # this is the same in proto/dist/ts btw
    deps: [proto:ts:build]
    cmds:
      - "{{.NPM}} i"
      - touch node_modules/.installed
    sources:
      - package.json
      - package-lock.json
      - pnpm-lock.yaml
    status:
      - test -f node_modules/.installed
  dev:
    deps: [prepare]
    cmd: "{{.NPX}} vite"
    env:
      CI: true
  build:
    deps: [prepare]
    cmds:
      - "{{.NPX}} tsc -b"
      - "{{.NPX}} vite build"
    sources:
      - src/**/*
      - public/**/*
      - package.json
    generates:
      - dist/**/*
  lint:
    deps: [prepare]
    cmd: "{{.NPX}} eslint --cache ."
  preview:
    deps: [build]
    cmd: "{{.NPX}} vite preview -- --host {{ .WEB_HOST }}:{{ .WEB_PORT }}"
    env:
      CI: true
  test:
    deps: [prepare]
    cmd: "{{.NPX}} vitest run"
